version: "3.9"

services:
  database_encomendei:
    image: postgres
    container_name: database_encomendei
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=encomendei
      - POSTGRES_PASSWORD=encomendei
      - POSTGRES_DB=encomendei
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: encomendei
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/encomendei
    links:
      - database_encomendei
    depends_on:
      - database_encomendei

volumes:
  pgdata:
    driver: local

